# Generated by Django 5.2a1 on 2026-03-06 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_onlystudies', '0007_blogpostvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('appointment_datetime__gte', models.F('created_at'))), name='appointment_datetime_not_before_created'),
        ),
        migrations.AddConstraint(
            model_name='blogpostvote',
            constraint=models.CheckConstraint(condition=models.Q(('value__in', [1, -1])), name='blog_post_vote_value_valid'),
        ),
        migrations.AddConstraint(
            model_name='forumanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_accepted', True)), fields=('question',), name='single_accepted_answer_per_question'),
        ),
    ]
